server:
  port: 8111
spring:
#  security:
#    user:
#      name: atguigu
#      password: atguigu

#mysql数据库连接
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.70.101:3306/demo?serverTimezone=GMT%2B8
      username: 'root'
      password: '050817'

mybatis:
  mapper-locations: classpath:mapper/*.xml